language: cpp
env:
  global:
  - FORCE_INSTALL=1
  - secure: mdPkBZcp5yTpbT3pfxoXt9ibMPnGxaKhGxgowutc/lTqGb2P+ki/GtbJ7+MriIIH3xmP6yGxyuSWHOD6TaZr3ol9tdPlN/sLGnveRVWlCEaFKkKh7JOzc526gqxcI0AVPJ/OJjz9rgmlUcZ55ZJOIVNJDh8MpIatT5U/N4JpbQINtzTrRi2CjU6Rg/6UWWFqEqhZfPDZDKgIHI2MPJvAbq3oPeZlxBJ96zYP29fDGfKvZJY86UY7bQWSjE76c+EegZ2EG5CrrowioKO0sURlhn+7kEp3GFcQnXBfeYY81AK5Gt1EGZQ5Louaf3C5k7YKNLDRMUuN+3XgihP30Rwaky4G9yaLkRud7B6FsfZVjHDWR9+46j5eKn7/cZOKulFY2WLUYZq7AFJRSZsR4kR0AM7yxw3paN8e/3iStPaeuE2KH4y2vCChJ0SCuuatc/A3/zNbVRZoBfq2yvrBhPXKma4L6Xcd9c/j3nfe1vkfloFBu+JljlCq2d28A4OYQsjAIwsorlgVOmhz6/Gfoq6+VLICiU+WzRSEhwijHD+CydCD0CkRP3MfhqkrDRGJIlRw2/czaFvTRjJOhlW+NTaFDcJEomO54jPWjKsmX/q80tT91EKslSWifNepICLAabaQwdrlgQ7TuIhs5PQlmA0gmIwwzBEcw9JmB4wqD/AUxj8=

matrix:
  include:
  - os: osx
    name: "Build macOS XCODE5"
    osx_image: xcode10.2
    compiler: clang

    script:
    - "./macbuild.tool"

    deploy:
      provider: releases
      skip_cleanup: true
      file:
      - Binaries/RELEASE/*.zip
      - Binaries/DEBUG/*.zip
      file_glob: true
      on:
        tags: true
      api_key:
        secure: Dtk7GX0mJlhbmYtpPaR5kTFCcRdBOEl5lEMSIODnxb+Oznwdjuj1iXsgG3WtmFY1yLShgHWAuVdHFCLcWWJIZ9bXRrkkZ75Tl3WPpNG48GVdc+ayyQrkCLYne3WIYTxd1NmXNceKfrQpD8O9R4IYQ5SJEY9d0L4KgLYvERtD5V6rsSX/T+OZZI1gTXFa9MvO6EQqfSGptXNTLZnkogZDB7bp/YZi46lFFaj3eutwEVEm9lEPjiND0L/zUjZXsEII7H7NocBSayJGWPGfFuiYa1lsQsEFAQyqbdgTa4+O1eby9qDJOaCHoFwbe2Fs7pi3fzegy2Jk4+zIleyuM0qXv26yS+gnDqmaruphXhXz+PtAkmw0sov40pKrbcHuRPfGx1lUX68PhqEg3S2vtKELPMhmLpRmy5dC8+dr4D7MJ3kQWCLy2vwrNg/EJJtsRhxg+h8Xo504g3aD7a4MOB/sAX0ITeiOZf9r0agxB69vpMaF5Jve7RrF9s0qGSSFA1L82U+WXywZr4qk/RG+ZjpnxlDJb3mMeTnAF1YrpIdsZrSL6eUWZACLpGrDLTTLGmMvgkqUEsXnFMQUovAIkEP3fzxU5mORTtLQu6kYP2fHJZXfI/HLmEFxnh4N43c7Tgh9biPAKHnABlA4csUl8Y4rRu72fQdEEq9cYxR4wFmAkhs=


  - os: linux
    name: "Build Linux CLANGPDB/GCC5"
    dist: xenial
    addons:
      apt:
        packages:
        - nasm
        - uuid-dev

    script:
    - export PYTHON_COMMAND=python3 # Something is broken in Travis CI environment, it asks for python3.7.
    - llvmfile="clang+llvm-9.0.1-x86_64-linux-gnu-ubuntu-16.04"
    - curl -LO "https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/${llvmfile}.tar.xz" || exit 1
    - llvmsum=$(shasum -a 256 "${llvmfile}.tar.xz" | cut -f1 -d' ')
    - llvmexpsum="1af280e96fec62acf5f3bb525e36baafe09f95f940dc9806e22809a83dfff4f8"
    - if [ "$llvmsum" != "$llvmexpsum" ]; then echo "Invalid LLVM checksum $llvmsum" ; exit 1 ; fi
    - tar -xf "${llvmfile}.tar.xz" || exit 1
    - export PATH="$(pwd)/${llvmfile}/bin:$PATH"
    - "./macbuild.tool"

  - os: linux
    name: "Build Linux CLANG38"
    dist: xenial
    addons:
      apt:
        packages:
        - nasm
        - uuid-dev
        - clang-8
        - llvm-8-dev

    script:
    - export PYTHON_COMMAND=python3 # Something is broken in Travis CI environment, it asks for python3.7.
    - sudo apt-get remove llvm-3.8 libllvm3.8 # Move LLVM 3.8 out of the way.
    - export PATH="/usr/lib/llvm-8/bin:$PATH" # Default compiler (7.0 or 3.8) has no LTO plugin.
    - export TOOLCHAINS=CLANG38
    - "./macbuild.tool"

  - os: osx
    name: "Analyze Coverity"
    osx_image: xcode10.2
    compiler: clang
    
    before_install:
      - curl -Ls https://entrust.com/root-certificates/entrust_l1k.cer -o ~/entrust_l1k.crt || exit 1
      - curl -LS https://curl.haxx.se/ca/cacert.pem -o ~/cacert.pem || exit 1
      - cat ~/entrust_l1k.crt >> ~/cacert.pem || exit 1
      - echo "cacert=\"$HOME/cacert.pem\"" > ~/.curlrc || exit 1
      - echo "ca_certificate=$HOME/cacert.pem" > ~/.wgetrc || exit 1

    script:
      - echo "This script runs coverity..."

    addons:
      coverity_scan:
        project:
          name: "acidanthera/AppleSupportPkg"
          description: "AppleSupportPkg"
        notification_email: $NOTIFICATION_EMAIL
        build_command_prepend: "./macbuild.tool --skip-build --skip-package && cd UDK ; src=$(curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/covstrap.sh) && eval \"$src\" || exit 1"
        build_command: "../macbuild.tool --skip-tests --skip-package RELEASE"
        branch_pattern: master
